name: Build, Test & Publish

on:
  push:
    branches:
      - 'master'
      - 'main'

permissions: write-all

env:
  COREDNS_VERSION: "1.11.1"
  COREDNS_DIST_VERSION: "2"

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v3

      - name: Pack packages
        run: |
          (cd ./npm/coredns-dist && npm run pre-release && npm pack)
          (cd ./npm/linux-arm64 && npm pack)
          (cd ./npm/linux-x64 && npm pack)
          (cd ./npm/darwin-arm64 && npm pack)
          (cd ./npm/darwin-x64 && npm pack)
          (cd ./npm/win32-x64 && npm pack)
      - name: List all files
        run: find

      - name: Upload bundle darwin-arm64
        uses: actions/upload-artifact@v3
        with:
          path: npm/darwin-arm64/coredns-dist-darwin-arm64-*.tgz
          name: coredns-dist-darwin-arm64.tgz
          if-no-files-found: error
      - name: Upload bundle darwin-x64
        uses: actions/upload-artifact@v3
        with:
          path: npm/darwin-x64/coredns-dist-darwin-x64-*.tgz
          name: coredns-dist-darwin-x64.tgz
          if-no-files-found: error
      - name: Upload bundle win32-x64
        uses: actions/upload-artifact@v3
        with:
          path: npm/win32-x64/coredns-dist-win32-x64-*.tgz
          name: coredns-dist-win32-x64.tgz
          if-no-files-found: error
      - name: Upload bundle linux-x64
        uses: actions/upload-artifact@v3
        with:
          path: npm/linux-x64/coredns-dist-linux-x64-*.tgz
          name: coredns-dist-linux-x64.tgz
          if-no-files-found: error
      - name: Upload bundle linux-arm64
        uses: actions/upload-artifact@v3
        with:
          path: npm/linux-arm64/coredns-dist-linux-arm64-*.tgz
          name: coredns-dist-linux-arm64.tgz
          if-no-files-found: error
      - name: Upload bundle coredns-dist
        uses: actions/upload-artifact@v3
        with:
          path: npm/coredns-dist/coredns-dist-*.tgz
          name: coredns-dist.tgz
          if-no-files-found: error

  test-linux-x64:
    runs-on: ubuntu-latest
    needs:
      - package
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - uses: actions/download-artifact@v3
        with:
          name: coredns-dist.tgz
      - uses: actions/download-artifact@v3
        with:
          name: coredns-dist-linux-x64.tgz
      - name: Run NPM Test
        working-directory: ./tests
        run: |
          npm i ../coredns-dist-*.tgz && npm test

  test-linux-arm64:
    runs-on: ubuntu-latest
    needs:
      - package
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: coredns-dist.tgz
      - uses: actions/download-artifact@v3
        with:
          name: coredns-dist-linux-arm64.tgz
      - name: Run testing
        uses: uraimo/run-on-arch-action@v2
        with:
          arch: aarch64
          distro: ubuntu22.04
          run: |
            apt update -q -y
            apt install -q -y curl bash sudo
            useradd -m otheruser
            cp ./coredns-dist-*.tgz tests/
            chmod -R 777 tests
            sudo -u otheruser bash -c 'curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash'
            sudo -u otheruser bash -c '. ~/.profile && nvm install v20 && (cd tests && npm i ./coredns-dist-*.tgz && npm test)'

  test-darwin-x64:
    runs-on: macos-latest
    needs:
      - package
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - uses: actions/download-artifact@v3
        with:
          name: coredns-dist.tgz
      - uses: actions/download-artifact@v3
        with:
          name: coredns-dist-darwin-x64.tgz
      - name: Run NPM Test
        working-directory: ./tests
        run: |
          npm i ../coredns-dist-*.tgz && npm test

  test-win32-x64:
    runs-on: windows-latest
    needs:
      - package
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - uses: actions/download-artifact@v3
        with:
          name: coredns-dist.tgz
      - uses: actions/download-artifact@v3
        with:
          name: coredns-dist-win32-x64.tgz
      - name: Run NPM Test
        working-directory: ./tests
        shell: bash
        run: |
          npm i ../coredns-dist-*.tgz && npm test

  test-darwin-arm64:
    runs-on: macos-latest-xlarge
    needs:
      - package
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - uses: actions/download-artifact@v3
        with:
          name: coredns-dist.tgz
      - uses: actions/download-artifact@v3
        with:
          name: coredns-dist-darwin-arm64.tgz
      - name: Run NPM Test
        working-directory: ./tests
        run: |
          npm i ../coredns-dist-*.tgz && npm test

  publish:
    runs-on: ubuntu-latest
    needs:
      - test-linux-x64
      - test-linux-arm64
      - test-darwin-x64
      - test-win32-x64
      - test-darwin-arm64
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
      - uses: actions/download-artifact@v3
        with:
          name: coredns-dist.tgz
      - uses: actions/download-artifact@v3
        with:
          name: coredns-dist-linux-x64.tgz
      - uses: actions/download-artifact@v3
        with:
          name: coredns-dist-linux-arm64.tgz
      - uses: actions/download-artifact@v3
        with:
          name: coredns-dist-darwin-x64.tgz
      - uses: actions/download-artifact@v3
        with:
          name: coredns-dist-win32-x64.tgz
      - uses: actions/download-artifact@v3
        with:
          name: coredns-dist-darwin-arm64.tgz
      - name: Run NPM Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm publish coredns-dist-v*.tgz
          npm publish coredns-dist-linux-x64-v*.tgz
          npm publish coredns-dist-linux-arm64-v*.tgz
          npm publish coredns-dist-darwin-x64-v*.tgz
          npm publish coredns-dist-win32-x64-v*.tgz
          npm publish coredns-dist-darwin-arm64-v*.tgz

  push:
    needs:
      - test-linux-x64
      - test-linux-arm64
      - test-darwin-x64
      - test-win32-x64
      - test-darwin-arm64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v3

      - name: Pack packages
        run: |
          (cd ./npm/coredns-dist && npm run pre-release && npm pack)
          (cd ./npm/linux-arm64 && npm pack)
          (cd ./npm/linux-x64 && npm pack)
          (cd ./npm/darwin-arm64 && npm pack)
          (cd ./npm/darwin-x64 && npm pack)
          (cd ./npm/win32-x64 && npm pack)

      - name: Check if there are any changes
        id: has_changes
        run: |
          git status || exit 1
          test -n "$(git status --porcelain)" && result=yes || result=no
          echo "result=$result" >> $GITHUB_OUTPUT

      - name: Commit changes
        if: steps.has_changes.outputs.result == 'yes'
        run: |
          git config --local user.email "github-actions@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add --all
          git commit -m "Autobuild: Built from ${{ github.sha }}"

      - name: Push changes back to origin
        if: steps.has_changes.outputs.result == 'yes'
        run: |
          # XXX: workaround for https://github.com/orgs/community/discussions/55820
          git config --global http.version HTTP/1.1
          git pull -r
          git push https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git master
